language: go
sudo: false

go: 1.13.x
before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/tsenart/deadcode
script:
    - make
    - make build-examples
    - make test
    - $GOPATH/bin/goveralls -service=travis-ci
    - deadcode pkg/mnemonic
